/**
 * This is an autogenerated file by update-third-parties.js
 */
import React from 'react'
import Script from 'next/script'

import Base from './base'

// Install a Google Analytics tag on your website
export function GoogleAnalytics(args: any) {
  return (
    <Base>
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${args.id}`}
        strategy="worker"
      />
      <Script
        id="google-analytics"
        strategy="worker"
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer=window.dataLayer||[];window.gtag=function gtag(){window.dataLayer.push(arguments);};gtag('js',new Date());gtag('config','${args.id}')`,
        }}
      />
    </Base>
  )
}

// Embed a Google Maps embed on your webpage
export function GoogleMapsEmbed(args: any) {
  return (
    <Base
      height={args.height || null}
      width={args.width || null}
      content={`<iframe loading="lazy" src="https://www.google.com/maps/embed/v1/${args.mapMode}?key=${args.apiKey}&${args.parameters}" width=${args.width} height=${args.height} style=${args.style} loading=${args.loading} allowfullscreen=${args.allowfullscreen} referrerpolicy="no-referrer-when-downgrade"></iframe>`}
    ></Base>
  )
}

// Embed a YouTube embed on your webpage.
export function YoutubeEmbed(args: any) {
  return (
    <Base
      height={args.height || null}
      width={args.width || null}
      content={`<lite-youtube videoid=${args.videoid} playlabel=${args.playlabel}></lite-youtube>`}
      stylesheets={[
        'https://cdn.jsdelivr.net/gh/paulirish/lite-youtube-embed@master/src/lite-yt-embed.css',
      ]}
    >
      <Script
        src={`https://cdn.jsdelivr.net/gh/paulirish/lite-youtube-embed@master/src/lite-yt-embed.js`}
        strategy="lazyOnload"
      />
    </Base>
  )
}
